# Dependencies
markdown:         redcarpet
highlighter:      pygments

plugins:
  - jekyll-paginate
  - jekyll-gist
# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            CodeMaker
tagline:          'Blog sobre projetos makers'
description:      'Este blog foi criado para mostrar projetos desenvolvidos no curso de Engenharia de Computação.'
url:              "http://matheus-pessoa16.github.io.com"
baseurl:          ""

author:
  name:           'Matheus Pessoa'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/matheus-pessoa16
