# Dependencies
markdown:         redcarpet
highlighter:      pygments



plugins:
  - jekyll-paginate
  - jekyll-gist
# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            CodeMake
tagline:          ''
description:      'Blog sobre projetos desenvolvidos na Engenharia de Computação.'
url:              'http://matheus-pessoa16.github.io.com'
baseurl:          "/blog"
includes:         ["images"]
author:
  name:           'Matheus Pessoa'
  url:            ''

paginate:         5



# Custom vars          

github:
  repo:           https://github.com/matheus-pessoa16

